export const HOME = '/'
export const JOB_BOARD = '/job-board'
export const LEARNING = '/learning-resources'
export const CONTACT = '/contact'
export const INDIVIDUAL_JOB = '/job'
export const POST_A_JOB = '/post-a-job'
