describe('Job Template', () => {
  it('tests first job on the jobs board', () => {
    cy.visit('/job-board/')
    cy.get("[data-cy='job-board-list']>a").first().click()
    cy.get("[data-cy='back-to-job-list']").click()
    cy.go('back')
    cy.get("[data-cy='job-title']").should('be', 'h2')
    cy.get("[data-cy='role-focus-and-position-type']")
    cy.get("[data-cy='job-description-title']").should('be', 'h3')
    cy.get("[data-cy='job-description']")
    cy.get("[data-cy='company-description-title']").should('be', 'h4')
    cy.get("[data-cy='company-description']")
    cy.get("[data-cy='company-logo']").should('have.attr', 'src')
    cy.get("[data-cy='company-name-sidebar']")
    cy.get("[data-cy='company-website']").should('have.attr', 'href')
    cy.get("[data-cy='how-to-apply']")
  })
})
